export const DATA = {
    NAME: {
        FIRST: 'Emily',
        LAST: 'Repech',
    },
    EXPERIENCE: {
        EXPERIENCE1: { 
            TITLE: 'Volunteer Coordinator',
            COMPANY: 'Ceres Community Project',
            STARTDATE: 'February 2018',
            ENDDATE: ' Present',
            LOCATION: 'Sebastopol, CA',
            DETAIL1: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
            DETAIL2: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
            DETAIL3: "It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            DETAIL4: '',
        },
        EXPERIENCE2: { 
            TITLE: 'Website and Social Media Coordinator',
            COMPANY: 'California Association of Environmental Professionals',
            STARTDATE: 'November 2017',
            ENDDATE: 'Present',
            LOCATION: 'San Diego, CA',
            DETAIL1: "I weekly update and post on the Santa Cruz - Silicon Valley chapter of the Association of Environmental Professionals' website and social media accounts.",
            DETAIL2: "I am responsible for updating the chapter's website using Joomla, and updating social media with upcoming chapter events and relevant media posts.",
            DETAIL3: '',
            DETAIL4: '',
        },
        EXPERIENCE3: { 
            TITLE: 'Grants Intern',
            COMPANY: 'California Association of Environmental Professionals',
            STARTDATE: 'August 2017',
            ENDDATE: 'October 2017',
            LOCATION: 'National City, CA',
            DETAIL1: "Wrote grant proposals, and researched potential funding sources related to environmental justice goals of the organization.",
            DETAIL2: "Social media campaigning which successfully increased ticket sales to events.",
            DETAIL3: '',
            DETAIL4: '',
        },
        EXPERIENCE4: { 
            TITLE: 'Outreach and Events Intern',
            COMPANY: 'Environmental Health Coalition',
            STARTDATE: 'August 2017',
            ENDDATE: 'October 2017',
            LOCATION: 'Santa Cruz, CA',
            DETAIL1: "Wrote grant proposals, and researched potential funding sources related to environmental justice goals of the organization.",
            DETAIL2: "Social media campaigning which successfully increased ticket sales to events.",
            DETAIL3: '',
            DETAIL4: '',
        },
        EXPERIENCE5: { 
            TITLE: 'Enforcement Intern',
            COMPANY: 'California Coastal Commission',
            STARTDATE: 'January 2017',
            ENDDATE: 'June 2017',
            LOCATION: 'Santa Cruz, CA',
            DETAIL1: "At the Coastal Commission, I carried out investigations into violations of the California Coastal Act.",
            DETAIL2: "Responsibilities included: researching the history of unpermitted development on coastal properties, identifying the violators of such unpermitted development, and researching the existence of any previous permitted/ unpermitted development.",
            DETAIL3: "Once sufficient data about a case was collected, I took action to inform property owners of their violations, and describe what remedies need to be made in order to become compliant with the California Coastal Act.",
            DETAIL4: "In most cases, this involved ceasing and removing the unpermitted development or obtaining a coastal development permit.",
        }
    },    
    EDUCATION: {
        DEGREE1: 'Bachelor of Arts in Environmental Studies with Honors',
        DEGREE2: 'Bachelor of Arts in Politics with Honors',
        COLLEGE: 'University of California, Santa Cruz',
        COLLEGESTARTDATE: 'September 2013',
        COLLEGEENDDATE: 'June 2017',
        HIGHSCHOOL: 'Analy High School',
        HIGHSTARTDATE: '',
        HIGHENDDATE: '',
    }      
}