export const DATA = {
    NAME: {
        FIRST: 'Emily',
        LAST: 'Repech',
    },
    EXPERIENCE: {
        EXPERIENCE1: { 
            TITLE: 'Volunteer Coordinator',
            COMPANY: 'Ceres Community Project',
            STARTDATE: 'February 2018',
            ENDDATE: ' Present',
            LOCATION: 'Sebastopol, CA',
            DETAIL1: "Creating a strong volunteer community by recruiting, onboarding, and managing volunteers",
            DETAIL2: "Facilitating community outreach and education on various sustainability topics",
            DETAIL3: "",
            DETAIL4: '',
        },
        EXPERIENCE2: { 
            TITLE: 'Website and Social Media Coordinator',
            COMPANY: 'California Association of Environmental Professionals',
            STARTDATE: 'November 2017',
            ENDDATE: 'February 2018',
            LOCATION: 'Santa Cruz, CA',
            DETAIL1: "Created weekly updates and blog posts on the Santa Cruz - Silicon Valley chapter's website and social media accounts",
            DETAIL2: "Pioneered and executed a social media strategy to increase engagement from members of the chapter using Joomla",
            DETAIL3: '',
            DETAIL4: '',
        },
        EXPERIENCE3: { 
            TITLE: 'Outreach and Events Intern',
            COMPANY: 'Surfrider Foundation, San Diego Chapter',
            STARTDATE: 'August 2017',
            ENDDATE: 'October 2017',
            LOCATION: 'San Diego, CA',
            DETAIL1: "Promoted local sustainability efforts by creating bi-weekly email newsletters using Mail Chimp",
            DETAIL2: "Facilitated beach cleanups, tabled local events, and assisted in planning and facilitating Surfrider events such as the Paddle for Clean Water",
            DETAIL3: 'Managed and coordinated volunteers',
            DETAIL4: '',
        },
        EXPERIENCE4: { 
            TITLE: 'Grants Intern',
            COMPANY: 'Environmental Health Coalition',
            STARTDATE: 'August 2017',
            ENDDATE: 'October 2017',
            LOCATION: 'National City, CA',
            DETAIL1: "Wrote grant proposals and compiled potential funding sources related to the environmental justice goals of the organization",
            DETAIL2: "Increased ticket sales to events via a social media compaign",
            DETAIL3: '',
            DETAIL4: '',
        },
        EXPERIENCE5: { 
            TITLE: 'Enforcement Intern',
            COMPANY: 'California Coastal Commission',
            STARTDATE: 'January 2017',
            ENDDATE: 'June 2017',
            LOCATION: 'Santa Cruz, CA',
            DETAIL1: "Carried out investigations into violations of the California Coastal Act",
            DETAIL2: "Investigated unpermitted development of coastal properties, identified the violators, and resolved violations appropriately",
        },
        EXPERIENCE6: { 
            TITLE: 'District and Government Relations Intern',
            COMPANY: 'Ygrene Energy Fund',
            STARTDATE: 'July 2015',
            ENDDATE: 'September 2015',
            LOCATION: 'Petaluma, CA',
            DETAIL1: "Created legal jurisdiction maps of Ygrene territory",
            DETAIL2: "Gained extensive experience in Excel and data entry",
        },
        EXPERIENCE7: { 
            TITLE: 'Crewmember',
            COMPANY: 'Singing Frogs Farm',
            STARTDATE: 'June 2014',
            ENDDATE: 'September 2014',
            LOCATION: 'Sebastopol, CA',
            DETAIL1: "Prepared field, planted and cared for new crops using 'no-till' methods",
            DETAIL2: "Harvested and packaged vegetables for the farm's Communited Supported Agriculture (CSA) members",
        },
        
    },    
    EDUCATION: {
        DEGREE1: 'Bachelor of Arts in Environmental Studies with Honors',
        DEGREE2: 'Bachelor of Arts in Politics with Honors',
        COLLEGE: 'University of California, Santa Cruz',
        COLLEGESTARTDATE: 'September 2013',
        COLLEGEENDDATE: 'June 2017',
        HIGHSCHOOL: 'Analy High School',
        HIGHSTARTDATE: '',
        HIGHENDDATE: '',
    }      
}